env:
  global:
  - secure: p50LlUdcMEaqC9+uZbm/sKYj2rilFhn0SA0L8Y27bfQczUxFrkrIJxFiB+iRvUoEY6q0M4YQoAuNLRqVjfolY/nzRrvNYx4QkNHsQZytcNnycPxM6Gx5H9XV1vcMkD2YEd49sHxdPc4WSXXMCMmOJZfKoQMpKnWHyKYrSlceWxFDJJJmXpNckTBp7lMWCYvHOzw2MrSXakfCYnndS1b1MBXkyWHACIVRgEEhBTMpjOE2gTZi/elyXrUMcBRxH1R4py3stmi62E91Lr62fIwQfbOQBZQpMDQSqs2BRgzL6Gy2S+OxDS9NLmiA9SzWlbb7fOlGh6O9w9Z3xduP5MBWds2n4iwkK1Z4EN1IZes3CaxVirD0zd/9W1JDs0jELTs5eQhhGClWL0DB0gyAw13ImEo9wSS/z3WfvfAmiKfzIUZaB/SIXZKNIyzVeIgllJQFMMkBm/dzYDwp59BQ4TuxPRNdaTrVlrrfog3EJfVaM3B/7hLalXwllY0ffZbpCx83ybWJ+MXXugr8kItmTvgQDZSbleGw8F3IKLfK1umL0c49aJI3gPZvef0sD12L6OzT3d97rFFdRaA/EBffWxMEt7H/4e2ZK0Cf0J8DlAx5VEtgkSi2AqTQuZ15noULl1T6rxM4xtInxhPJK1LDRZHSgtjZzTTZZq170ZcbATusob4=
  - secure: cdDahpTg1ndTZyXpW1J3822ALQANbKh6btrHL8C7jjNUyE5/AjUPdXhZRuJnMpCXutzFRUbcvVly7ozv+lMMveycUjCeBbZ39aqkFESjTYxK5H4z+MhM39V8yn8BZ3xbp1AQU5dfEFYUnDbdyH80LNlOsWebXqKO6jIdJfdeBBKdZb0amN4jK981LKKjecM4ws3gCptkm/GUOCJ0SLtdr4TFPIpVe7fu8QwFcunOlhW8QikiXBQueD5ULgcayyGSObWnXhQXmsgMkhI9jze4wSWgmIeL1YhG3Ild/EoUZ/3dHa4sO8zQYjcQ5VxvnNzmV9gYDIv+S/LyLPWMH9jBcHlTvtVJOwtyx3JGScv7FWiTrjq8cvDVrrAd7UwejmZJ4t+2074UUs/2bhq+NDMhdjNETBqkDW1UA/Y3Zl/6hf6MMUDO8YkTSKxraWOp7FmaMPOm9zjHPAe0Ez1BhVOqczclj2jr4L8NTKS7Ackpqo7URT45SmWjQHlwtSG3b4ywPR8QI1FMl0Bp6Wsj2+ejxFv16OJXJL1EnYR+jxfD4xXZGjGFD4/ZRqkT697u6HcErPC8+uMI04NmZME79v2eyZ+u9C3ncXRzZZvjJafWX/uBs1JvTV1B7ZyYBeZyrdwT4/oyqJV8pgbazeK4T0wo0S3SQPuWs/InFjPrQghBCsY=

services:
- docker

addons:
  sonarcloud:
    organization: departement-loire-atlantiqu-1
    token:
      secure: FpHIr4m+k7Wyzbp2tXHDI7k6pr3mMkRdaPvdEZqpeWUdOELB6sHcehxA3ctG0GT+17bW7l1DKWADQz491oEkElw7X7X3LAi86vQyZHEBkESud0SQJTs2h384rNz2HhqXcz/eut+EMM2PhqbKyUHr1LC6pDw6tq9uArOIubUAm+jLuiaxJPQkOu7jjbC/s95F3w+5AZMliAp5DNN5gTeKjeNtdU59SHrzeg+mCxTB4sZJmk3T1vJoMwbTGmdCFHqY1eQ8HIS1umezS10HF5iLrGPSTbPMmUm18WLTj8DFz2ekiBEKNgQHujIATphVYwHLg49xXuuCuDG3M2RjvK5WuBeTkWIIXsyGwKmEWJ/Nr58TYGbqe26nUBhDR5KHHe3qPUdvSCFAAi6L7jx/U7FJKiYwwzrvIEZ80vp7A93RUGiOqg6yLP6VNFtRE86P0qpZSPA/umKKq89Ci37WHtjvlZUxS5A8hO+llSNVXoO3cNFzS3Qc1gjuP/l6lmBkbCmCZXg6U/xbz7lEVY38VWJnXhG+92vg7MWydlHqbBsPAV+soJKx2NwyIFtNungRxQoHfZPth4AieInXglyU5MiiGD1bYOuxfbQyDYGvzzH/Y9NJXe6DtLgw2FUz2+P0Jhwn+PkAwBCRXd7WBkqx4qJOd/kqYeFSSCNtgvAFptnyB3Q=

before_script:
- echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
- docker pull asfram/jplatformbuild:1.1

script:
- docker run -v ${TRAVIS_BUILD_DIR}:/root/source --name buildimage -t asfram/jplatformbuild:1.1
- docker cp buildimage:/root/dist .
- export CODE_VERSION=`git describe`
- sonar-scanner -Dsonar.projectVersion=$CODE_VERSION

deploy:
  provider: releases
  api_key:
    secure: MX1eY0R4t1ZgYvc+KOVt+K9L4EQb21rpcbujW6yZbI4bddjRhT9qRJUdNrav1nn0w3aUWEth9O8l2bvwrrWXZ4ouYHX+x8XHE+wzjMN+GwLJIq2n4h2bYniJ0zA3BbeHsGVQ64hbkjHXTc83Ls19vXx3MZgy0qJnX58jQ8+YHSwae/ReRl1MBYi9mPVek8eZGKH2fodYw7Wt5bAzSHxXR8o6r5nAa42avNbsoijPag/XoVGbCgKMl4LUFcxdOifgYgM91tWAg5x7oqkccD+Sr6g+mfEEySou4p9Snw6kz1+viXhSpIuA3jn1Afdr+Jhdzxho2k4I6rcL/cPQ3wBHS0kgA7c4J0UQYU+2LS72ysir/pQ9gcNjOfSYs25/LuGuECyCvDUsNAfBgqjtwQQGmRPSnQbkgHji6COeBAuFOja3uphgnOBIOZqOtrNKkOYcJGlBiv2S4BzjAAEAGyo5oXGzR0qQNrDZyQvtNF5Z/7vl758tNnuOLztn1PiHqZtke/Fb2zG/xFf54yrssndsi4u29vNbpzBVkQyZtpVRZJb352azBbmm3jZ1RMgMDfCJBNe/QeftEjkSYvQ66iXMKbXGW71tMBh48Wvy+PglA6UqEUQUzGIA9kVsE2KTsvy7hYYVQyWC32L4ygCcPXprA9tMppgTEZgAaG3ZTu51Ka8=
  file_glob: true
  file: "${TRAVIS_BUILD_DIR}/dist/*.zip"
  skip_cleanup: true
  on:
    tags: true
